-- ═══════════════════════════════════════════════════════════════
-- Hospital ER Management System — Oracle Schema
-- ═══════════════════════════════════════════════════════════════

-- ── Sequences ──────────────────────────────────────────────────
CREATE SEQUENCE SEQ_PATIENTS    START WITH 10001 INCREMENT BY 1  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADMISSIONS  START WITH 20001 INCREMENT BY 1  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BEDS        START WITH 1     INCREMENT BY 1  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DOCTORS     START WITH 1     INCREMENT BY 1  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LAB_ORDERS  START WITH 30001 INCREMENT BY 1  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_VITALS      START WITH 40001 INCREMENT BY 1  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ALERTS      START WITH 50001 INCREMENT BY 1  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MEDICATIONS START WITH 60001 INCREMENT BY 1  NOCACHE NOCYCLE;

-- ── Staff / Doctors ────────────────────────────────────────────
CREATE TABLE ER_DOCTORS (
    DOCTOR_ID       NUMBER(10)    NOT NULL,
    STAFF_ID        VARCHAR2(15)  NOT NULL,
    FULL_NAME       VARCHAR2(100) NOT NULL,
    SPECIALIZATION  VARCHAR2(50)  NOT NULL,
    SHIFT           VARCHAR2(10)  DEFAULT 'DAY' NOT NULL,   -- DAY, NIGHT, EVENING
    STATUS          VARCHAR2(20)  DEFAULT 'AVAILABLE' NOT NULL,
    MAX_PATIENTS    NUMBER(3)     DEFAULT 3,
    CURRENT_LOAD    NUMBER(3)     DEFAULT 0,
    YEARS_EXPERIENCE NUMBER(3),
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ER_DOCTORS    PRIMARY KEY (DOCTOR_ID),
    CONSTRAINT UQ_STAFF_ID      UNIQUE (STAFF_ID),
    CONSTRAINT CK_DOCTOR_STATUS CHECK (STATUS IN ('AVAILABLE','BUSY','ON_BREAK','OFF_DUTY'))
);
CREATE INDEX IDX_DOCTOR_STATUS ON ER_DOCTORS(STATUS);
CREATE INDEX IDX_DOCTOR_SHIFT  ON ER_DOCTORS(SHIFT);

-- ── ER Beds ────────────────────────────────────────────────────
CREATE TABLE ER_BEDS (
    BED_ID          NUMBER(10)    NOT NULL,
    BED_NUMBER      VARCHAR2(10)  NOT NULL,
    WARD            VARCHAR2(30)  NOT NULL,   -- TRIAGE, CRITICAL, GENERAL, ISOLATION, TRAUMA
    STATUS          VARCHAR2(20)  DEFAULT 'AVAILABLE' NOT NULL,
    PATIENT_ID      NUMBER(10),
    ASSIGNED_AT     TIMESTAMP,
    EQUIPMENT_FLAGS VARCHAR2(200),           -- JSON: ventilator, monitor, etc.
    FLOOR_NUMBER    NUMBER(2),
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ER_BEDS       PRIMARY KEY (BED_ID),
    CONSTRAINT UQ_BED_NUMBER    UNIQUE (BED_NUMBER),
    CONSTRAINT CK_BED_STATUS    CHECK (STATUS IN ('AVAILABLE','OCCUPIED','CLEANING','MAINTENANCE'))
);
CREATE INDEX IDX_BED_STATUS ON ER_BEDS(STATUS);
CREATE INDEX IDX_BED_WARD   ON ER_BEDS(WARD);

-- ── Patients ───────────────────────────────────────────────────
CREATE TABLE ER_PATIENTS (
    PATIENT_ID      NUMBER(10)    NOT NULL,
    MRN             VARCHAR2(20)  NOT NULL,   -- Medical Record Number
    FULL_NAME       VARCHAR2(100) NOT NULL,
    DATE_OF_BIRTH   DATE          NOT NULL,
    GENDER          VARCHAR2(10)  NOT NULL,
    BLOOD_TYPE      VARCHAR2(5),
    CONTACT_PHONE   VARCHAR2(15),
    EMERGENCY_CONTACT VARCHAR2(100),
    ALLERGIES       VARCHAR2(500),
    CHRONIC_CONDITIONS VARCHAR2(500),
    INSURANCE_ID    VARCHAR2(30),
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ER_PATIENTS   PRIMARY KEY (PATIENT_ID),
    CONSTRAINT UQ_PATIENT_MRN   UNIQUE (MRN)
);
CREATE INDEX IDX_PATIENT_MRN  ON ER_PATIENTS(MRN);
CREATE INDEX IDX_PATIENT_NAME ON ER_PATIENTS(FULL_NAME);

-- ── ER Admissions (the core workflow entity) ────────────────────
CREATE TABLE ER_ADMISSIONS (
    ADMISSION_ID        NUMBER(10)    NOT NULL,
    ADMISSION_REF       VARCHAR2(20)  NOT NULL,
    PATIENT_ID          NUMBER(10)    NOT NULL,
    CHIEF_COMPLAINT     VARCHAR2(500) NOT NULL,
    TRIAGE_LEVEL        NUMBER(1)     NOT NULL,   -- 1=Immediate 2=Emergent 3=Urgent 4=Less-Urgent 5=Non-Urgent
    TRIAGE_SCORE        NUMBER(5,2),              -- ESI score
    STATUS              VARCHAR2(30)  DEFAULT 'WAITING_TRIAGE' NOT NULL,
    ASSIGNED_DOCTOR_ID  NUMBER(10),
    BED_ID              NUMBER(10),
    ARRIVAL_TIME        TIMESTAMP     NOT NULL,
    TRIAGE_TIME         TIMESTAMP,
    DOCTOR_ASSIGNED_AT  TIMESTAMP,
    BED_ASSIGNED_AT     TIMESTAMP,
    TREATMENT_STARTED_AT TIMESTAMP,
    DISCHARGED_AT       TIMESTAMP,
    DIAGNOSIS           VARCHAR2(1000),
    TREATMENT_NOTES     CLOB,
    DISCHARGE_TYPE      VARCHAR2(20),             -- DISCHARGED, ADMITTED, TRANSFERRED, DECEASED
    PRIORITY_QUEUE_POS  NUMBER(5),               -- position in triage queue
    PROCESSING_THREAD   VARCHAR2(100),           -- which thread processed this admission
    CREATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ADMISSIONS       PRIMARY KEY (ADMISSION_ID),
    CONSTRAINT UQ_ADMISSION_REF    UNIQUE (ADMISSION_REF),
    CONSTRAINT FK_ADM_PATIENT      FOREIGN KEY (PATIENT_ID)         REFERENCES ER_PATIENTS(PATIENT_ID),
    CONSTRAINT FK_ADM_DOCTOR       FOREIGN KEY (ASSIGNED_DOCTOR_ID) REFERENCES ER_DOCTORS(DOCTOR_ID),
    CONSTRAINT FK_ADM_BED          FOREIGN KEY (BED_ID)             REFERENCES ER_BEDS(BED_ID),
    CONSTRAINT CK_TRIAGE_LEVEL     CHECK (TRIAGE_LEVEL BETWEEN 1 AND 5),
    CONSTRAINT CK_ADM_STATUS       CHECK (STATUS IN (
        'WAITING_TRIAGE','IN_TRIAGE','WAITING_BED','WAITING_DOCTOR',
        'IN_TREATMENT','UNDER_OBSERVATION','WAITING_DISCHARGE',
        'DISCHARGED','ADMITTED','TRANSFERRED'))
);
CREATE INDEX IDX_ADM_PATIENT   ON ER_ADMISSIONS(PATIENT_ID);
CREATE INDEX IDX_ADM_DOCTOR    ON ER_ADMISSIONS(ASSIGNED_DOCTOR_ID);
CREATE INDEX IDX_ADM_BED       ON ER_ADMISSIONS(BED_ID);
CREATE INDEX IDX_ADM_STATUS    ON ER_ADMISSIONS(STATUS);
CREATE INDEX IDX_ADM_TRIAGE    ON ER_ADMISSIONS(TRIAGE_LEVEL);
CREATE INDEX IDX_ADM_ARRIVAL   ON ER_ADMISSIONS(ARRIVAL_TIME);

-- ── Vital Signs ────────────────────────────────────────────────
CREATE TABLE VITAL_SIGNS (
    VITAL_ID        NUMBER(10)    NOT NULL,
    ADMISSION_ID    NUMBER(10)    NOT NULL,
    PATIENT_ID      NUMBER(10)    NOT NULL,
    HEART_RATE      NUMBER(5,1),       -- bpm
    BLOOD_PRESSURE_S NUMBER(5,1),      -- systolic mmHg
    BLOOD_PRESSURE_D NUMBER(5,1),      -- diastolic mmHg
    TEMPERATURE     NUMBER(5,2),       -- Celsius
    OXYGEN_SAT      NUMBER(5,2),       -- SpO2 %
    RESP_RATE       NUMBER(5,1),       -- breaths/min
    PAIN_SCALE      NUMBER(2),         -- 0-10
    GCS_SCORE       NUMBER(2),         -- Glasgow Coma Scale 3-15
    IS_CRITICAL     NUMBER(1)  DEFAULT 0,
    RECORDED_BY     VARCHAR2(100),
    RECORDED_AT     TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_VITALS        PRIMARY KEY (VITAL_ID),
    CONSTRAINT FK_VITAL_ADM     FOREIGN KEY (ADMISSION_ID) REFERENCES ER_ADMISSIONS(ADMISSION_ID)
);
CREATE INDEX IDX_VITAL_ADM     ON VITAL_SIGNS(ADMISSION_ID);
CREATE INDEX IDX_VITAL_PATIENT ON VITAL_SIGNS(PATIENT_ID);
CREATE INDEX IDX_VITAL_CRIT    ON VITAL_SIGNS(IS_CRITICAL);
CREATE INDEX IDX_VITAL_TIME    ON VITAL_SIGNS(RECORDED_AT);

-- ── Lab Orders ─────────────────────────────────────────────────
CREATE TABLE LAB_ORDERS (
    LAB_ORDER_ID    NUMBER(10)    NOT NULL,
    ORDER_REF       VARCHAR2(20)  NOT NULL,
    ADMISSION_ID    NUMBER(10)    NOT NULL,
    PATIENT_ID      NUMBER(10)    NOT NULL,
    TEST_TYPE       VARCHAR2(50)  NOT NULL,  -- CBC, BMP, TROPONIN, X-RAY, CT, etc.
    PRIORITY        VARCHAR2(10)  DEFAULT 'ROUTINE' NOT NULL,  -- STAT, URGENT, ROUTINE
    STATUS          VARCHAR2(20)  DEFAULT 'ORDERED' NOT NULL,
    RESULT_VALUE    VARCHAR2(500),
    RESULT_FLAG     VARCHAR2(10),  -- NORMAL, HIGH, LOW, CRITICAL
    ORDERED_BY      VARCHAR2(100),
    ORDERED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_AT    TIMESTAMP,
    TURNAROUND_MINS NUMBER(5),
    PROCESSING_THREAD VARCHAR2(100),
    CONSTRAINT PK_LAB_ORDERS    PRIMARY KEY (LAB_ORDER_ID),
    CONSTRAINT UQ_ORDER_REF     UNIQUE (ORDER_REF),
    CONSTRAINT FK_LAB_ADM       FOREIGN KEY (ADMISSION_ID) REFERENCES ER_ADMISSIONS(ADMISSION_ID),
    CONSTRAINT CK_LAB_PRIORITY  CHECK (PRIORITY IN ('STAT','URGENT','ROUTINE')),
    CONSTRAINT CK_LAB_STATUS    CHECK (STATUS IN ('ORDERED','IN_PROGRESS','COMPLETED','CANCELLED'))
);
CREATE INDEX IDX_LAB_ADMISSION ON LAB_ORDERS(ADMISSION_ID);
CREATE INDEX IDX_LAB_STATUS    ON LAB_ORDERS(STATUS);
CREATE INDEX IDX_LAB_PRIORITY  ON LAB_ORDERS(PRIORITY);

-- ── Alerts ─────────────────────────────────────────────────────
CREATE TABLE ER_ALERTS (
    ALERT_ID        NUMBER(10)    NOT NULL,
    ADMISSION_ID    NUMBER(10),
    PATIENT_ID      NUMBER(10),
    ALERT_TYPE      VARCHAR2(50)  NOT NULL,  -- CRITICAL_VITALS, CODE_BLUE, SEPSIS_RISK, etc.
    SEVERITY        VARCHAR2(10)  NOT NULL,  -- CRITICAL, HIGH, MEDIUM, LOW
    MESSAGE         VARCHAR2(1000) NOT NULL,
    IS_ACKNOWLEDGED NUMBER(1)    DEFAULT 0,
    ACKNOWLEDGED_BY VARCHAR2(100),
    ACKNOWLEDGED_AT TIMESTAMP,
    AUTO_RESOLVED   NUMBER(1)    DEFAULT 0,
    TRIGGERED_BY    VARCHAR2(100),
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ALERTS        PRIMARY KEY (ALERT_ID),
    CONSTRAINT CK_ALERT_SEV     CHECK (SEVERITY IN ('CRITICAL','HIGH','MEDIUM','LOW'))
);
CREATE INDEX IDX_ALERT_ADM    ON ER_ALERTS(ADMISSION_ID);
CREATE INDEX IDX_ALERT_SEV    ON ER_ALERTS(SEVERITY);
CREATE INDEX IDX_ALERT_ACK    ON ER_ALERTS(IS_ACKNOWLEDGED);
CREATE INDEX IDX_ALERT_TIME   ON ER_ALERTS(CREATED_AT);

-- ── Medications ────────────────────────────────────────────────
CREATE TABLE MEDICATIONS (
    MED_ID          NUMBER(10)    NOT NULL,
    ADMISSION_ID    NUMBER(10)    NOT NULL,
    DRUG_NAME       VARCHAR2(100) NOT NULL,
    DOSAGE          VARCHAR2(50)  NOT NULL,
    ROUTE           VARCHAR2(20)  NOT NULL,  -- IV, ORAL, IM, etc.
    FREQUENCY       VARCHAR2(30),
    STATUS          VARCHAR2(20)  DEFAULT 'ORDERED',
    ORDERED_BY      VARCHAR2(100),
    ORDERED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    ADMINISTERED_AT TIMESTAMP,
    CONSTRAINT PK_MEDICATIONS   PRIMARY KEY (MED_ID),
    CONSTRAINT FK_MED_ADM       FOREIGN KEY (ADMISSION_ID) REFERENCES ER_ADMISSIONS(ADMISSION_ID)
);
CREATE INDEX IDX_MED_ADM ON MEDICATIONS(ADMISSION_ID);

-- ── Seed: Doctors ──────────────────────────────────────────────
INSERT INTO ER_DOCTORS(DOCTOR_ID,STAFF_ID,FULL_NAME,SPECIALIZATION,SHIFT,STATUS,MAX_PATIENTS,YEARS_EXPERIENCE) VALUES
(SEQ_DOCTORS.NEXTVAL,'DR001','Dr. Arun Sharma','Emergency Medicine','DAY','AVAILABLE',4,12);
INSERT INTO ER_DOCTORS(DOCTOR_ID,STAFF_ID,FULL_NAME,SPECIALIZATION,SHIFT,STATUS,MAX_PATIENTS,YEARS_EXPERIENCE) VALUES
(SEQ_DOCTORS.NEXTVAL,'DR002','Dr. Priya Menon','Emergency Medicine','DAY','AVAILABLE',4,8);
INSERT INTO ER_DOCTORS(DOCTOR_ID,STAFF_ID,FULL_NAME,SPECIALIZATION,SHIFT,STATUS,MAX_PATIENTS,YEARS_EXPERIENCE) VALUES
(SEQ_DOCTORS.NEXTVAL,'DR003','Dr. Rahul Nair','Trauma Surgery','DAY','AVAILABLE',3,15);
INSERT INTO ER_DOCTORS(DOCTOR_ID,STAFF_ID,FULL_NAME,SPECIALIZATION,SHIFT,STATUS,MAX_PATIENTS,YEARS_EXPERIENCE) VALUES
(SEQ_DOCTORS.NEXTVAL,'DR004','Dr. Sunita Patel','Cardiology','DAY','AVAILABLE',3,10);
INSERT INTO ER_DOCTORS(DOCTOR_ID,STAFF_ID,FULL_NAME,SPECIALIZATION,SHIFT,STATUS,MAX_PATIENTS,YEARS_EXPERIENCE) VALUES
(SEQ_DOCTORS.NEXTVAL,'DR005','Dr. Vikram Singh','Neurology','NIGHT','AVAILABLE',3,9);
INSERT INTO ER_DOCTORS(DOCTOR_ID,STAFF_ID,FULL_NAME,SPECIALIZATION,SHIFT,STATUS,MAX_PATIENTS,YEARS_EXPERIENCE) VALUES
(SEQ_DOCTORS.NEXTVAL,'DR006','Dr. Meera Iyer','Pediatric Emergency','DAY','AVAILABLE',5,7);

-- ── Seed: ER Beds ──────────────────────────────────────────────
BEGIN
  -- Critical Care Beds
  FOR i IN 1..4 LOOP
    INSERT INTO ER_BEDS(BED_ID,BED_NUMBER,WARD,STATUS,EQUIPMENT_FLAGS,FLOOR_NUMBER)
    VALUES(SEQ_BEDS.NEXTVAL,'CC-'||LPAD(i,2,'0'),'CRITICAL','AVAILABLE','["ventilator","monitor","iv_pump"]',1);
  END LOOP;
  -- Trauma Bays
  FOR i IN 1..3 LOOP
    INSERT INTO ER_BEDS(BED_ID,BED_NUMBER,WARD,STATUS,EQUIPMENT_FLAGS,FLOOR_NUMBER)
    VALUES(SEQ_BEDS.NEXTVAL,'TR-'||LPAD(i,2,'0'),'TRAUMA','AVAILABLE','["monitor","defibrillator","crash_cart"]',1);
  END LOOP;
  -- General ER Beds
  FOR i IN 1..12 LOOP
    INSERT INTO ER_BEDS(BED_ID,BED_NUMBER,WARD,STATUS,EQUIPMENT_FLAGS,FLOOR_NUMBER)
    VALUES(SEQ_BEDS.NEXTVAL,'ER-'||LPAD(i,2,'0'),'GENERAL','AVAILABLE','["monitor","iv_pump"]',2);
  END LOOP;
  -- Isolation Rooms
  FOR i IN 1..4 LOOP
    INSERT INTO ER_BEDS(BED_ID,BED_NUMBER,WARD,STATUS,EQUIPMENT_FLAGS,FLOOR_NUMBER)
    VALUES(SEQ_BEDS.NEXTVAL,'IS-'||LPAD(i,2,'0'),'ISOLATION','AVAILABLE','["monitor","negative_pressure"]',2);
  END LOOP;
  -- Triage Bays
  FOR i IN 1..6 LOOP
    INSERT INTO ER_BEDS(BED_ID,BED_NUMBER,WARD,STATUS,EQUIPMENT_FLAGS,FLOOR_NUMBER)
    VALUES(SEQ_BEDS.NEXTVAL,'TG-'||LPAD(i,2,'0'),'TRIAGE','AVAILABLE','["basic_monitor"]',1);
  END LOOP;
END;
/

COMMIT;