-- ════════════════════════════════════════════════════════════════
-- Stock Order Processing Engine — Oracle Schema
-- ════════════════════════════════════════════════════════════════

-- ── Sequences ────────────────────────────────────────────────────
CREATE SEQUENCE SEQ_ORDERS    START WITH 100001 INCREMENT BY 100 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TRADES    START WITH 200001 INCREMENT BY 100 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ACCOUNTS  START WITH 300001 INCREMENT BY 50  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_POSITIONS START WITH 400001 INCREMENT BY 50  NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ALERTS    START WITH 500001 INCREMENT BY 50  NOCACHE NOCYCLE;

-- ── Trading Accounts ─────────────────────────────────────────────
CREATE TABLE TRADING_ACCOUNTS (
    ACCOUNT_ID      NUMBER(19)    NOT NULL,
    CLIENT_ID       VARCHAR2(20)  NOT NULL,
    CLIENT_NAME     VARCHAR2(100) NOT NULL,
    EMAIL           VARCHAR2(100) NOT NULL,
    CASH_BALANCE    NUMBER(19,4)  DEFAULT 0 NOT NULL,
    BLOCKED_AMOUNT  NUMBER(19,4)  DEFAULT 0 NOT NULL,
    DAILY_MTM       NUMBER(19,4)  DEFAULT 0,
    STATUS          VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
    SEGMENT         VARCHAR2(10)  DEFAULT 'EQ' NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION_NUM     NUMBER(19)    DEFAULT 0,
    CONSTRAINT PK_TRADING_ACCOUNTS  PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT UQ_CLIENT_ID         UNIQUE (CLIENT_ID),
    CONSTRAINT UQ_ACCOUNT_EMAIL     UNIQUE (EMAIL),
    CONSTRAINT CK_ACCOUNT_STATUS    CHECK (STATUS IN ('ACTIVE','SUSPENDED','CLOSED'))
);
CREATE INDEX IDX_ACCOUNT_CLIENT ON TRADING_ACCOUNTS(CLIENT_ID);
CREATE INDEX IDX_ACCOUNT_STATUS ON TRADING_ACCOUNTS(STATUS);

-- ── Orders ───────────────────────────────────────────────────────
CREATE TABLE STOCK_ORDERS (
    ORDER_ID            NUMBER(19)    NOT NULL,
    ORDER_REF           VARCHAR2(30)  NOT NULL,
    ACCOUNT_ID          NUMBER(19)    NOT NULL,
    CLIENT_ID           VARCHAR2(20)  NOT NULL,
    SYMBOL              VARCHAR2(20)  NOT NULL,
    EXCHANGE            VARCHAR2(10)  DEFAULT 'NSE' NOT NULL,
    ORDER_TYPE          VARCHAR2(20)  NOT NULL,   -- MARKET, LIMIT, STOP_LOSS, BRACKET
    SIDE                VARCHAR2(10)  NOT NULL,   -- BUY, SELL
    QUANTITY            NUMBER(15)    NOT NULL,
    FILLED_QTY          NUMBER(15)    DEFAULT 0,
    REMAINING_QTY       NUMBER(15)    NOT NULL,
    PRICE               NUMBER(15,4),             -- null for MARKET orders
    TRIGGER_PRICE       NUMBER(15,4),             -- for stop-loss
    AVG_FILL_PRICE      NUMBER(15,4)  DEFAULT 0,
    STATUS              VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    VALIDITY            VARCHAR2(10)  DEFAULT 'DAY' NOT NULL,  -- DAY, IOC, GTC
    PRODUCT             VARCHAR2(10)  DEFAULT 'CNC' NOT NULL,  -- CNC, MIS, NRML
    DISCLOSED_QTY       NUMBER(15)    DEFAULT 0,
    REJECTION_REASON    VARCHAR2(500),
    SUBMITTED_AT        TIMESTAMP     NOT NULL,
    MATCHED_AT          TIMESTAMP,
    CANCELLED_AT        TIMESTAMP,
    CREATED_BY          VARCHAR2(50),
    CONSTRAINT PK_STOCK_ORDERS      PRIMARY KEY (ORDER_ID),
    CONSTRAINT UQ_ORDER_REF         UNIQUE (ORDER_REF),
    CONSTRAINT FK_ORDER_ACCOUNT     FOREIGN KEY (ACCOUNT_ID) REFERENCES TRADING_ACCOUNTS(ACCOUNT_ID),
    CONSTRAINT CK_ORDER_TYPE        CHECK (ORDER_TYPE IN ('MARKET','LIMIT','STOP_LOSS','BRACKET','SL_MARKET')),
    CONSTRAINT CK_ORDER_SIDE        CHECK (SIDE IN ('BUY','SELL')),
    CONSTRAINT CK_ORDER_STATUS      CHECK (STATUS IN ('PENDING','OPEN','PARTIALLY_FILLED','FILLED','CANCELLED','REJECTED','EXPIRED'))
);
CREATE INDEX IDX_ORDER_ACCOUNT  ON STOCK_ORDERS(ACCOUNT_ID);
CREATE INDEX IDX_ORDER_SYMBOL   ON STOCK_ORDERS(SYMBOL);
CREATE INDEX IDX_ORDER_STATUS   ON STOCK_ORDERS(STATUS);
CREATE INDEX IDX_ORDER_SIDE     ON STOCK_ORDERS(SIDE, SYMBOL);
CREATE INDEX IDX_ORDER_SUBMIT   ON STOCK_ORDERS(SUBMITTED_AT);

-- ── Trades (matched orders) ──────────────────────────────────────
CREATE TABLE TRADES (
    TRADE_ID            NUMBER(19)    NOT NULL,
    TRADE_REF           VARCHAR2(30)  NOT NULL,
    BUY_ORDER_ID        NUMBER(19)    NOT NULL,
    SELL_ORDER_ID       NUMBER(19)    NOT NULL,
    BUY_ACCOUNT_ID      NUMBER(19)    NOT NULL,
    SELL_ACCOUNT_ID     NUMBER(19)    NOT NULL,
    SYMBOL              VARCHAR2(20)  NOT NULL,
    EXCHANGE            VARCHAR2(10)  NOT NULL,
    QUANTITY            NUMBER(15)    NOT NULL,
    PRICE               NUMBER(15,4)  NOT NULL,
    TRADE_VALUE         NUMBER(19,4)  NOT NULL,
    BROKERAGE_BUY       NUMBER(10,4)  DEFAULT 0,
    BROKERAGE_SELL      NUMBER(10,4)  DEFAULT 0,
    STT                 NUMBER(10,4)  DEFAULT 0,
    GST                 NUMBER(10,4)  DEFAULT 0,
    SETTLEMENT_DATE     DATE,
    SETTLEMENT_STATUS   VARCHAR2(20)  DEFAULT 'PENDING',
    EXECUTED_AT         TIMESTAMP     NOT NULL,
    SETTLED_AT          TIMESTAMP,
    THREAD_NAME         VARCHAR2(100), -- tracks which thread executed this trade
    CONSTRAINT PK_TRADES            PRIMARY KEY (TRADE_ID),
    CONSTRAINT UQ_TRADE_REF         UNIQUE (TRADE_REF),
    CONSTRAINT FK_TRADE_BUY_ORDER   FOREIGN KEY (BUY_ORDER_ID)  REFERENCES STOCK_ORDERS(ORDER_ID),
    CONSTRAINT FK_TRADE_SELL_ORDER  FOREIGN KEY (SELL_ORDER_ID) REFERENCES STOCK_ORDERS(ORDER_ID)
);
CREATE INDEX IDX_TRADE_SYMBOL   ON TRADES(SYMBOL);
CREATE INDEX IDX_TRADE_BUY_ACC  ON TRADES(BUY_ACCOUNT_ID);
CREATE INDEX IDX_TRADE_SELL_ACC ON TRADES(SELL_ACCOUNT_ID);
CREATE INDEX IDX_TRADE_EXECUTED ON TRADES(EXECUTED_AT);
CREATE INDEX IDX_TRADE_STATUS   ON TRADES(SETTLEMENT_STATUS);

-- ── Market Data (real-time price store) ──────────────────────────
CREATE TABLE MARKET_DATA (
    SYMBOL          VARCHAR2(20)  NOT NULL,
    EXCHANGE        VARCHAR2(10)  NOT NULL,
    LTP             NUMBER(15,4)  NOT NULL,   -- Last Traded Price
    OPEN_PRICE      NUMBER(15,4),
    HIGH_PRICE      NUMBER(15,4),
    LOW_PRICE       NUMBER(15,4),
    CLOSE_PRICE     NUMBER(15,4),
    VOLUME          NUMBER(19)    DEFAULT 0,
    BID_PRICE       NUMBER(15,4),
    ASK_PRICE       NUMBER(15,4),
    BID_QTY         NUMBER(15)    DEFAULT 0,
    ASK_QTY         NUMBER(15)    DEFAULT 0,
    CIRCUIT_HIGH    NUMBER(15,4),
    CIRCUIT_LOW     NUMBER(15,4),
    WEEK_52_HIGH    NUMBER(15,4),
    WEEK_52_LOW     NUMBER(15,4),
    MARKET_CAP      NUMBER(19,4),
    PE_RATIO        NUMBER(10,2),
    UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_MARKET_DATA   PRIMARY KEY (SYMBOL, EXCHANGE)
);

-- ── Positions ────────────────────────────────────────────────────
CREATE TABLE POSITIONS (
    POSITION_ID     NUMBER(19)    NOT NULL,
    ACCOUNT_ID      NUMBER(19)    NOT NULL,
    SYMBOL          VARCHAR2(20)  NOT NULL,
    EXCHANGE        VARCHAR2(10)  NOT NULL,
    PRODUCT         VARCHAR2(10)  NOT NULL,
    NET_QTY         NUMBER(15)    DEFAULT 0,
    BUY_QTY         NUMBER(15)    DEFAULT 0,
    SELL_QTY        NUMBER(15)    DEFAULT 0,
    AVG_BUY_PRICE   NUMBER(15,4)  DEFAULT 0,
    AVG_SELL_PRICE  NUMBER(15,4)  DEFAULT 0,
    REALIZED_PNL    NUMBER(19,4)  DEFAULT 0,
    UNREALIZED_PNL  NUMBER(19,4)  DEFAULT 0,
    DAY_CHANGE_PCT  NUMBER(8,4)   DEFAULT 0,
    LAST_UPDATED    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_POSITIONS         PRIMARY KEY (POSITION_ID),
    CONSTRAINT UQ_POSITION_ACC_SYM  UNIQUE (ACCOUNT_ID, SYMBOL, PRODUCT),
    CONSTRAINT FK_POSITION_ACCOUNT  FOREIGN KEY (ACCOUNT_ID) REFERENCES TRADING_ACCOUNTS(ACCOUNT_ID)
);
CREATE INDEX IDX_POSITION_ACCOUNT ON POSITIONS(ACCOUNT_ID);
CREATE INDEX IDX_POSITION_SYMBOL  ON POSITIONS(SYMBOL);

-- ── Price Alerts ─────────────────────────────────────────────────
CREATE TABLE PRICE_ALERTS (
    ALERT_ID        NUMBER(19)    NOT NULL,
    ACCOUNT_ID      NUMBER(19)    NOT NULL,
    SYMBOL          VARCHAR2(20)  NOT NULL,
    ALERT_TYPE      VARCHAR2(20)  NOT NULL,   -- PRICE_ABOVE, PRICE_BELOW, PCT_CHANGE
    TARGET_VALUE    NUMBER(15,4)  NOT NULL,
    CURRENT_VALUE   NUMBER(15,4),
    STATUS          VARCHAR2(20)  DEFAULT 'ACTIVE',
    TRIGGERED_AT    TIMESTAMP,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PRICE_ALERTS  PRIMARY KEY (ALERT_ID),
    CONSTRAINT FK_ALERT_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES TRADING_ACCOUNTS(ACCOUNT_ID)
);

-- ── Seed market data ─────────────────────────────────────────────
INSERT INTO MARKET_DATA(SYMBOL,EXCHANGE,LTP,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,VOLUME,BID_PRICE,ASK_PRICE,CIRCUIT_HIGH,CIRCUIT_LOW,WEEK_52_HIGH,WEEK_52_LOW,PE_RATIO) VALUES
('RELIANCE','NSE',2947.50,2920.00,2960.00,2910.00,2938.40,5234100,2947.00,2948.00,3232.00,2644.00,3024.90,2220.30,27.8);
INSERT INTO MARKET_DATA(SYMBOL,EXCHANGE,LTP,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,VOLUME,BID_PRICE,ASK_PRICE,CIRCUIT_HIGH,CIRCUIT_LOW,WEEK_52_HIGH,WEEK_52_LOW,PE_RATIO) VALUES
('TCS','NSE',4123.75,4090.00,4145.00,4080.00,4110.20,1876200,4123.00,4124.50,4521.00,3700.00,4592.25,3445.55,31.2);
INSERT INTO MARKET_DATA(SYMBOL,EXCHANGE,LTP,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,VOLUME,BID_PRICE,ASK_PRICE,CIRCUIT_HIGH,CIRCUIT_LOW,WEEK_52_HIGH,WEEK_52_LOW,PE_RATIO) VALUES
('INFY','NSE',1834.20,1820.00,1845.00,1815.00,1829.65,3421800,1834.00,1834.50,2012.00,1640.00,1999.80,1358.35,28.4);
INSERT INTO MARKET_DATA(SYMBOL,EXCHANGE,LTP,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,VOLUME,BID_PRICE,ASK_PRICE,CIRCUIT_HIGH,CIRCUIT_LOW,WEEK_52_HIGH,WEEK_52_LOW,PE_RATIO) VALUES
('HDFCBANK','NSE',1689.90,1675.00,1698.00,1670.00,1682.35,6543200,1689.50,1690.25,1850.00,1512.00,1880.00,1363.55,20.1);
INSERT INTO MARKET_DATA(SYMBOL,EXCHANGE,LTP,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,VOLUME,BID_PRICE,ASK_PRICE,CIRCUIT_HIGH,CIRCUIT_LOW,WEEK_52_HIGH,WEEK_52_LOW,PE_RATIO) VALUES
('WIPRO','NSE',524.60,520.00,528.00,518.00,522.85,4234700,524.50,524.75,575.00,471.00,611.00,395.25,22.6);
INSERT INTO MARKET_DATA(SYMBOL,EXCHANGE,LTP,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,VOLUME,BID_PRICE,ASK_PRICE,CIRCUIT_HIGH,CIRCUIT_LOW,WEEK_52_HIGH,WEEK_52_LOW,PE_RATIO) VALUES
('ICICIBANK','NSE',1247.30,1235.00,1252.00,1230.00,1241.60,7123400,1247.00,1247.60,1368.00,1118.00,1376.20,932.25,19.8);
INSERT INTO MARKET_DATA(SYMBOL,EXCHANGE,LTP,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,VOLUME,BID_PRICE,ASK_PRICE,CIRCUIT_HIGH,CIRCUIT_LOW,WEEK_52_HIGH,WEEK_52_LOW,PE_RATIO) VALUES
('BHARTIARTL','NSE',1456.80,1445.00,1462.00,1440.00,1451.20,2345600,1456.50,1457.00,1597.00,1304.00,1612.50,1101.30,72.4);
INSERT INTO MARKET_DATA(SYMBOL,EXCHANGE,LTP,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,VOLUME,BID_PRICE,ASK_PRICE,CIRCUIT_HIGH,CIRCUIT_LOW,WEEK_52_HIGH,WEEK_52_LOW,PE_RATIO) VALUES
('SBIN','NSE',823.45,815.00,827.00,812.00,819.80,8934500,823.00,823.90,899.00,733.00,912.10,543.25,10.2);

-- ── Seed trading accounts ────────────────────────────────────────
INSERT INTO TRADING_ACCOUNTS(ACCOUNT_ID,CLIENT_ID,CLIENT_NAME,EMAIL,CASH_BALANCE,STATUS,SEGMENT) VALUES
(SEQ_ACCOUNTS.NEXTVAL,'ACC001','Arjun Sharma','arjun@tradepro.in',500000.00,'ACTIVE','EQ');
INSERT INTO TRADING_ACCOUNTS(ACCOUNT_ID,CLIENT_ID,CLIENT_NAME,EMAIL,CASH_BALANCE,STATUS,SEGMENT) VALUES
(SEQ_ACCOUNTS.NEXTVAL,'ACC002','Priya Nair','priya@tradepro.in',250000.00,'ACTIVE','EQ');
INSERT INTO TRADING_ACCOUNTS(ACCOUNT_ID,CLIENT_ID,CLIENT_NAME,EMAIL,CASH_BALANCE,STATUS,SEGMENT) VALUES
(SEQ_ACCOUNTS.NEXTVAL,'ACC003','Rajan Kumar','rajan@tradepro.in',1000000.00,'ACTIVE','EQ');
INSERT INTO TRADING_ACCOUNTS(ACCOUNT_ID,CLIENT_ID,CLIENT_NAME,EMAIL,CASH_BALANCE,STATUS,SEGMENT) VALUES
(SEQ_ACCOUNTS.NEXTVAL,'ACC004','AlgoTrader Bot','algo@tradepro.in',5000000.00,'ACTIVE','EQ');

COMMIT;